name: Q6 - Archive Java File with Date and Diff

on:
  push:
    paths:
      - "Q6.java"

jobs:
  archive-and-diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Q6_archive_date.txt
      run: |
        CURRENT_DATE=$(date '+%d-%m-%Y-%H%M%S')
        echo "Nom : Donovan Lefevre" > "Q6_archive_${CURRENT_DATE}.txt"
        echo "" >> "Q6_archive_${CURRENT_DATE}.txt"
        echo "Contenu de Q6.java :" >> "Q6_archive_${CURRENT_DATE}.txt"
        cat Q6.java >> "Q6_archive_${CURRENT_DATE}.txt"
        
        echo "" >> "Q6_archive_${CURRENT_DATE}.txt"
        echo "Taille du fichier Q6.java (en caractères et lignes) :" >> "Q6_archive_${CURRENT_DATE}.txt"
        wc Q6.java >> "Q6_archive_${CURRENT_DATE}.txt"

    - name: Create Q6_différences.txt
      run: |
        PREVIOUS_FILE=$(ls | grep -E "Q6_archive_\d{2}-\d{2}-\d{4}-\d{6}.txt" | sort | tail -n 2 | head -n 1)
        
        if [ -n "$PREVIOUS_FILE" ]; then
          echo "Comparaison entre les fichiers Q6_archive_${CURRENT_DATE}.txt et $PREVIOUS_FILE" > "Q6_différences.txt"
          echo "" >> "Q6_différences.txt"
          diff $PREVIOUS_FILE "Q6_archive_${CURRENT_DATE}.txt" >> "Q6_différences.txt"
        else
          echo "Aucun fichier précédent trouvé pour la comparaison." > "Q6_différences.txt"
        fi

    - name: Configure Git
      run: |
        git config --global user.name "DonovanLef"
        git config --global user.email "donovan.lefevre@etu.univ-lehavre.fr"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        CURRENT_DATE=$(date '+%d-%m-%Y-%H%M%S')
        echo "Fichiers à ajouter : Q6_archive_${CURRENT_DATE}.txt et Q6_différences.txt"
        git add "Q6_archive_${CURRENT_DATE}.txt" "Q6_différences.txt"
        git commit -m "Update Q6_archive and Q6_différences files"
        git push origin main
