name: Q6 - Archive Java File with Date

on:
  push:
    paths:
      - "Q6.java"

jobs:
  archive-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Define CURRENT_DATE
      id: define_date
      run: |
        CURRENT_DATE=$(date '+%d-%m-%Y-%H%M%S')
        echo "CURRENT_DATE=$CURRENT_DATE" >> $GITHUB_ENV

    - name: Create Q6_archive_date.txt
      run: |
        echo "Nom : Donovan Lefevre" > "Q6_archive_${CURRENT_DATE}.txt"
        echo "" >> "Q6_archive_${CURRENT_DATE}.txt"
        echo "Contenu de Q6.java :" >> "Q6_archive_${CURRENT_DATE}.txt"
        cat Q6.java >> "Q6_archive_${CURRENT_DATE}.txt"

    - name: Configure Git
      run: |
        git config --global user.name "DonovanLef"
        git config --global user.email "donovan.lefevre@etu.univ-lehavre.fr"

    - name: Commit or stash local changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Des modifications locales non indexées ont été trouvées."
          git add .
          git commit -m "Committing untracked changes before pull"
        else
          echo "Aucune modification locale non indexée."
        fi

    - name: Pull latest changes
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/DonovanLef/R5-07-DS.git
        git pull origin main --rebase

    - name: Create Q6_différences.txt
      run: |
        FILES=$(ls Q6_archive_*.txt | sort)
        if [ $(echo "$FILES" | wc -l) -ge 2 ]; then
          PREVIOUS_FILE=$(echo "$FILES" | tail -n 2 | head -n 1)
          echo "Comparaison entre Q6_archive_${CURRENT_DATE}.txt et $PREVIOUS_FILE" > "Q6_différences.txt"
          echo "" >> "Q6_différences.txt"
          diff $PREVIOUS_FILE "Q6_archive_${CURRENT_DATE}.txt" >> "Q6_différences.txt"
        else
          echo "Aucun fichier précédent trouvé pour la comparaison." > "Q6_différences.txt"
        fi

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add "Q6_archive_${CURRENT_DATE}.txt"
        git add "Q6_différences.txt"
        git commit -m "Add Q6_archive_${CURRENT_DATE}.txt and Q6_différences.txt"
        git push origin main
